# Generated by Django 5.0.2 on 2024-02-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank='True', null='True', upload_to='user/', verbose_name='Аватар'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank='True', max_length=35, null='True', verbose_name='Страна'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank='True', max_length=35, null='True', verbose_name='Номер телефона'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='189365414705', max_length=15, verbose_name='Проверочный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
