# Generated by Django 5.0.2 on 2024-03-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='365513889728', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
