# Generated by Django 5.0.2 on 2024-02-27 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_lesson', models.CharField(max_length=50, verbose_name='название урока')),
                ('description_lesson', models.TextField(verbose_name='описание урока')),
                ('image_lesson', models.ImageField(blank='True', null='True', upload_to='lesson/', verbose_name='картинка урока')),
                ('url_lesson', models.URLField(blank='True', null='True', verbose_name='ссылка на видео')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='дата выхода урока')),
                ('author', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url_course', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='ссылка на курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
